Repository epinio/helm-charts, pull requests merged in 2021-12, with the labels that each got.

#31 Improve Helm Chart CI pipeline
  .github/workflows/lint-test.yml
  .github/workflows/main-ci.yml
  .github/workflows/release.yml
  chart/epinio-installer/.helmignore
  chart/epinio-installer/Chart.yaml
  chart/epinio-installer/ci/k3d-values.yaml
  ct/ct-install.yaml
  ct/ct.yaml
Labels: enhancement

#37 Fix certmanager in epinioserver issue
  chart/epinio-installer/Chart.yaml
  chart/epinio-installer/templates/NOTES.txt
  chart/epinio-installer/templates/manifest.yaml
Labels: bug

#27 Automate Epinio-server update for the chart epinio
  .github/workflows/updatecli.yml
  updatecli/updatecli.d/epinio.yaml
  updatecli/values.yaml
Labels: enhancement

#44 Add option to specify a custom TLS issuer
  chart/epinio-installer/questions.yml
  chart/epinio-installer/templates/manifest.yaml
Labels: bug

#52 Build and publish charts locally for the CI
  .github/increment-version.sh
  .github/workflows/main-ci.yml
  Makefile
  scripts/build-charts-ci.sh
Labels: devops admin

#47 Add epinio-installer manifest for updatecli
  updatecli/updatecli.d/epinio-installer.yaml
  updatecli/updatecli.d/epinio.yaml
Labels: epinio-installer, epinio
