Repository epinio/helm-charts, pull requests merged in 2022-10, with the labels that each got.

#274 Add epinio repo add instruction
  chart/epinio/README.md
Labels: documentation

#281 Enable Updatecli autodiscovery feature
  .github/workflows/updatecli.yml
  updatecli/updatecli.d/autodiscovery.yaml
  updatecli/updatecli.d/epinio-ui.yaml
  updatecli/updatecli.d/epinio.yaml
  updatecli/updatecli.d/epinio/epinioui.yaml
  updatecli/updatecli.d/epinio/kubed.yaml
  updatecli/updatecli.d/epinio/minio.yaml
Labels: dependencies

#286 Bump nginx version. Low-hanging fruit in CVE work
  chart/epinio/values.yaml
Labels: bug

#288 Tweaked the chart description
  chart/epinio/Chart.yaml
Labels: documentation

#289 fix: missing quoting to prevent mis-interpretation as numbers
  chart/epinio/templates/default-user.yaml
Labels: bug
