Repository epinio/helm-charts, pull requests merged in 2022-09, with the labels that each got.

#264 Support app(chart) customization
  chart/epinio/crds/app-crd.yaml
  chart/epinio/crds/appcharts-crd.yaml
Labels: enhancement

#267 Introduce extraEnv for server deployment
  chart/epinio/templates/server.yaml
  chart/epinio/values.yaml
Labels: bug

#276 Trial a `bci-micro` derived image as replacement for `library/bash`.
  chart/epinio/templates/stage-scripts.yaml
  chart/epinio/values.yaml
Labels: spike

#252 Integrate DEX as sub chart
  chart/epinio/Chart.lock
  chart/epinio/Chart.yaml
  chart/epinio/charts/dex-0.11.0.tgz
  chart/epinio/templates/dex.yaml
  chart/epinio/templates/server.yaml
  chart/epinio/values.yaml
  ct/ct-install.yaml
  ct/ct.yaml
Labels: enhancement, spike
