Repository epinio/helm-charts, pull requests merged in 2022-04, with the labels that each got.

#154 Use createNodePort functionality all the time with containerregistry.enabled
  chart/epinio/templates/container-registry.yaml
  chart/epinio/values.yaml
Labels: enhancement

#161 Update UI image and changes following 0.6.2
  chart/epinio-ui/Chart.yaml
  chart/epinio-ui/templates/server.yaml
  chart/epinio-ui/values.yaml
Labels: dependencies, epinio-ui

#153 Fixed and extended epinio values schema
  chart/epinio/values.schema.json
  chart/epinio/values.yaml
Labels: bug
