Repository epinio/helm-charts, pull requests merged in 2022-01, with the labels that each got.

#59 AWS secret key must be password type
  chart/epinio-installer/questions.yml
Labels: enhancement

#58 Do not rotate minio access keys on re-install/upgrade of epinio
  chart/epinio-installer/templates/manifest.yaml
Labels: bug

#65 Fix some broken links in README
  README.md
  chart/epinio-installer/README.md
  chart/epinio/README.md
Labels: documentation

#67 Mention Epinio menu to control Epinio (Rancher)
  chart/epinio-installer/templates/NOTES.txt
Labels: documentation
