Repository epinio/helm-charts, pull requests merged in 2022-03, with the labels that each got.

#120 Fix outdated links in README
  chart/epinio/README.md
Labels: documentation

#116 Fix unwanted irrelevant error messages from the staging scripts
  chart/epinio/templates/stage-scripts.yaml
Labels: bug

#105 Deploy, update, and remove applications via helm - chart
  chart/application/.helmignore
  chart/application/Chart.yaml
  chart/application/templates/_helpers.tpl
  chart/application/templates/deployment.yaml
  chart/application/templates/ingress.yaml
  chart/application/templates/service.yaml
  chart/application/values.yaml
  chart/epinio/templates/app-crd.yaml
  chart/epinio/templates/server.yaml
Labels: enhancement

#127 simplify app chart - remove owner references
  chart/application/Chart.yaml
  chart/application/templates/deployment.yaml
  chart/application/templates/ingress.yaml
  chart/application/templates/service.yaml
  chart/application/values.yaml
Labels: enhancement

#125 Remove registry ingress
  chart/epinio/templates/_helpers.tpl
  chart/epinio/templates/certificate.yaml
  chart/epinio/templates/container-registry.yaml
  chart/epinio/templates/registry-secret.yaml
  chart/epinio/templates/staging-namespace.yaml
Labels: enhancement

#141 Fix zip archive support in staging
  chart/epinio/templates/stage-scripts.yaml
Labels: bug

#140 Fix some missing chart annotations (keywords, logo, sources, home)
  chart/application/Chart.yaml
  chart/application/values.yaml
  chart/epinio-ui/Chart.yaml
  chart/epinio/Chart.yaml
Labels: documentation

#142 Add option to pass map of annotations to API ingress
  chart/epinio/templates/ingress.yaml
  chart/epinio/values.yaml
Labels: enhancement

#146 Run epinio server as non-root
  chart/epinio/templates/server.yaml
Labels: enhancement

#148 Provide Image References for Staging Support To Kube Resources
  chart/epinio/templates/container-registry.yaml
  chart/epinio/templates/server.yaml
  chart/epinio/templates/stage-scripts.yaml
  chart/epinio/values.yaml
Labels: bug

#150 Rancher Marketplace Integration: Moved the app CRD yaml into the directory expected by the rancher tooling.
  chart/epinio/crds/app-crd.yaml
Labels: bug
