Repository epinio/helm-charts, pull requests merged in 2023-02, with the labels that each got.

#349 Added `stagingServiceAccountName` env var
  chart/epinio/templates/server.yaml
  chart/epinio/values.yaml
Labels: kind/enhancement

#324 s3gw integration
  .github/workflows/release.yml
  chart/epinio/Chart.lock
  chart/epinio/Chart.yaml
  chart/epinio/README.md
  chart/epinio/charts/s3gw-0.11.0.tgz
  chart/epinio/questions.yml
  chart/epinio/templates/_helpers.tpl
  chart/epinio/templates/chart-validations.yaml
  chart/epinio/templates/s3-secret.yaml
  chart/epinio/templates/server.yaml
  chart/epinio/values.schema.json
  chart/epinio/values.yaml
  ct/ct-install.yaml
  ct/ct.yaml
Labels: area/aws

#373 Fixed check for uiClientSecret value
  chart/epinio/templates/dex.yaml
Labels: kind/bug

#370 fix: create nicer-named replacement for `email` template variable
  chart/epinio/questions.yml
  chart/epinio/templates/cluster-issuers.yaml
  chart/epinio/values.schema.json
  chart/epinio/values.yaml
Labels: kind/enhancement

#376 fix: annotation to allow websocket service in EKS 1.24+
  chart/epinio/templates/ingress.yaml
Labels: kind/bug, area/aws

#378 Fixed epinio-ui deployment with disabled dex
  chart/epinio-ui/Chart.yaml
  chart/epinio-ui/templates/server.yaml
Labels: kind/bug, area/epinio-ui
