Repository epinio/helm-charts, pull requests merged in 2023-10, with the labels that each got.

#499 remove traefik annotations for cluster issuer ingresses
  chart/epinio/templates/cluster-issuers.yaml
Labels: kind/bug

#500 bump nginx to 1.25.2-alpine. fixes a number of security issues.
  chart/epinio/values.yaml
Labels: kind/bug, area/dependencies

#503 bump aws-cli to newer version
  chart/epinio/values.yaml
Labels: area/dependencies, area/aws

#505 Updated staging script removing `-process-type` flag
  chart/epinio/templates/stage-scripts.yaml
Labels: kind/enhancement

#502 Support/switch to `builder-jammy`
  chart/epinio/templates/server.yaml
  chart/epinio/templates/stage-scripts-bionic.yaml
  chart/epinio/templates/stage-scripts-jammy.yaml
  chart/epinio/templates/stage-scripts.yaml
  chart/epinio/values.yaml
Labels: kind/enhancement, area/dependencies
