Repository epinio/helm-charts, pull requests merged in 2023-04, with the labels that each got.

#399 Add doc references to staging script
  chart/epinio/templates/stage-scripts.yaml
Labels: area/documentation

#401 Fixup app chart for upgrading
  chart/application-stateful/Chart.yaml
  chart/application-stateful/templates/_helpers.tpl
  chart/application/Chart.yaml
  chart/application/templates/_helpers.tpl
  chart/epinio/templates/default-app-chart.yaml
Labels: kind/bug

#410 fix: make env variables directly availabe to creator, not just creator's children
  chart/epinio/templates/stage-scripts.yaml
Labels: kind/bug

#419 feat: updated app CRD in chart
  chart/epinio/crds/app-crd.yaml
Labels: kind/enhancement

#421 Added minimum to appListeningPort in default app chart
  chart/epinio/templates/default-app-chart.yaml
Labels: kind/bug
