Repository epinio/helm-charts, pull requests merged in 2023-01, with the labels that each got.

#326 Custom annotations also for dex's ingress
  chart/epinio/templates/dex.yaml
Labels: enhancement

#331 Fix templating for disabled dex
  chart/epinio/templates/server.yaml
Labels: kind/bug

#332 Bump minio dependency to 5.0.4
  chart/epinio/Chart.lock
  chart/epinio/Chart.yaml
  chart/epinio/charts/minio-5.0.1.tgz
  chart/epinio/charts/minio-5.0.4.tgz
Labels: area/dependencies

#333 security: bump aws cli to 2.9.14.
  chart/epinio/values.yaml
Labels: area/aws

#341 Remove the dex cert fighting with the ingress derived dex-tls cert over the dex-tls secret
  chart/epinio/templates/dex.yaml
Labels: kind/bug
