Repository epinio/helm-charts, pull requests merged in 2023-06, with the labels that each got.

#435 Added `strategy` to Epinio deployment
  chart/epinio/templates/server.yaml
  chart/epinio/values.yaml
Labels: kind/enhancement

#438 feat: expose the registry certificate secret to users of the Rancher marketplace integration
  chart/epinio/questions.yml
Labels: kind/enhancement

#441 Bump service class CRD for setting support.
  chart/epinio/crds/appcharts-crd.yaml
  chart/epinio/crds/service-crd.yaml
Labels: kind/enhancement

#444 Fixed some `updatecli` issues
  updatecli/updatecli.d/epinio-ui.yaml
  updatecli/updatecli.d/epinio.yaml
Labels: kind/bug

#452 Rollback s3gw to `0.14.0`
  chart/epinio/Chart.lock
  chart/epinio/Chart.yaml
  chart/epinio/charts/s3gw-0.14.0.tgz
  chart/epinio/charts/s3gw-0.17.0.tgz
Labels: dependencies
