Repository epinio/helm-charts, pull requests merged in 2023-11, with the labels that each got.

#509 experimental excision of cert-manager
  chart/epinio/templates/cert-secrets.yaml
  chart/epinio/templates/certificate.yaml
  chart/epinio/templates/cluster-issuers.yaml
  chart/epinio/templates/container-registry.yaml
  chart/epinio/templates/ui/certificate.yaml
  chart/epinio/values.yaml
Labels: area/dependencies

#511 dropped epinio-ui cert, and associated epinio-ui-tls secret
  chart/epinio/templates/cert-secrets.yaml
  chart/epinio/templates/ui/certificate.yaml
  chart/epinio/templates/ui/ingress.yaml
  chart/epinio/values.yaml
Labels: kind/chore

#506 New Authorization roles
  chart/epinio/templates/default-user.yaml
  chart/epinio/templates/dex.yaml
  chart/epinio/values.schema.json
  chart/epinio/values.yaml
Labels: kind/enhancement

#512 Updated Github actions
  .github/workflows/build-epiniod.yml
  .github/workflows/main-ci.yml
  .github/workflows/release.yml
  .github/workflows/sync-readme.yml
  .github/workflows/updatecli.yml
Labels: area/dependencies

#523 detect single directory as app source and lift contents to match paketo's expectations
  chart/epinio/templates/stage-scripts.yaml
Labels: kind/enhancement

#524 fix: handling of EVs in staging, when no EVs are present at all
  chart/epinio/templates/stage-scripts.yaml
Labels: kind/bug

#525 Update user role to have namespace write permissions
  chart/epinio/templates/default-user.yaml
Labels: kind/bug

#526 Place CNB_PLATFORM_API into the specs for staging scripts
  chart/epinio/templates/stage-scripts-bionic.yaml
  chart/epinio/templates/stage-scripts-jammy.yaml
  chart/epinio/templates/stage-scripts.yaml
Labels: kind/enhancement
