Repository epinio/helm-charts, pull requests merged in 2023-07, with the labels that each got.

#458 Expose location of default app chart tarball for configuration by operators
  chart/epinio/templates/default-app-chart.yaml
  chart/epinio/values.yaml
Labels: kind/enhancement

#463 set s3gw's defaultUserCredentialsSecret value in values.yaml
  chart/epinio/values.yaml
Labels: kind/bug

#467 Revert `s3gw` to `0.14.0`
  chart/epinio/Chart.lock
  chart/epinio/Chart.yaml
  chart/epinio/charts/s3gw-0.14.0.tgz
  chart/epinio/charts/s3gw-0.18.0.tgz
Labels: area/dependencies

#477 fix mishandling of env assignments with spaces in var name and/or value
  chart/epinio/templates/stage-scripts.yaml
Labels: kind/bug
